
# Boshabitats

# Inleiding




# Toekennen van habitattype aan de meetpunten van de Bosinventarisatie 

```{r getDataHabtypes, cache = TRUE, }

connectionStrata <- odbcConnectAccess2007(dbStrata)

VBI_plots_N2000 <- sqlFetch(connectionStrata,"tblN2000Habitat_versie2017-01-01" )

odbcClose(connectionStrata)


```


```{r figureHabtypes, cache = TRUE, }

ggplot(VBI_plots_N2000, aes(x = Phab)) + geom_histogram(binwidth = 10) + facet_wrap(~ HabCode, scales =  "free")


```


```{r selectieplots, cache = TRUE, }

VBI_plots_selection <- VBI_plots_N2000 %>%
  filter(Phab >= 70) %>%
  group_by(HabCode) %>%
  dplyr::mutate(nPlots = n()) %>%
  filter(nPlots > 20)

### Aanduiding van VBI-plots die al opgemeten werden in 2de cyclus

connectionMeetproces <- odbcConnectAccess2007(dbMeetproces)

recordsVBI2 <- sqlFetch(connectionMeetproces, "tblRecordsVBI2+")
recordsVBI1 <- sqlFetch(connectionMeetproces, "tblRecordsVBI1")
plotCordinates <- sqlFetch(connectionMeetproces,"tblCoordinaten")
plotDetails <- sqlFetch(connectionMeetproces,"tblPlotDetails")

odbcClose(connectionMeetproces)

VBI_plots_selection$VBI1 <- ifelse(VBI_plots_selection$IDPlots %in% recordsVBI1$IDPlots, 1,0)
VBI_plots_selection$VBI2 <- ifelse(VBI_plots_selection$IDPlots %in% recordsVBI2$IDPlots, 1,0)

VBI_plots_selection %>%
  group_by(HabCode) %>%
  dplyr::summarise(nVBI1 = sum(VBI1),
            nVBI2 = sum(VBI2)) %>%
  kable()

VBI_plots_selection <- VBI_plots_selection %>%
  ungroup()

gepaardePlots <- filter(plotDetails, Periode == 2 & StartPeriode == 1) 

plotsVBI2 <- filter(plotDetails, Periode == 2)




```


# Berekening van analysevariabelen voor LSVI-indicatoren

```{r calculateAV, cache = TRUE}

### Berekening LSVI-indicatoren m.b.t. habitatstructuur
test <- 1


plotHabtypesVBI2 <- VBI_plots_selection %>%
  filter(VBI2 == 1) %>%
  dplyr::select(IDPlots, HabCode)

VBI2_LSVI_Structuur <- calculateLSVI_dendroVBI2(plotHabtypes = plotHabtypesVBI2, niveau = "plot")

# ophalen bedekking soorten uit vegetatieopname
coverSpeciesVBI2 <- getCoverSpeciesVBI2(plotIDs = plotHabtypesVBI2$IDPlots)

# ophalen bedekking vegetatielagen
coverVegLayersVBI2 <- getCoverVeglayersVBI2(plotIDs = plotHabtypesVBI2$IDPlots)

# berekening indicatoren op basis van vegetatieopname
VBI2_LSVI_Vegetatie <- calculateLSVI_vegetatieopname(plotHabtypes = plotHabtypesVBI2, bedekkingSoorten = coverSpeciesVBI2, bedekkingVeglagen = coverVegLayersVBI2)

VBI2_LSVI <- bind_rows(VBI2_LSVI_Structuur, VBI2_LSVI_Vegetatie) %>%
              arrange(IDPlots, Criterium)

### Berekening LSVI-indicatoren m.b.t. habitatstructuur

plotHabtypesVBI1 <- VBI_plots_selection %>%
  filter(VBI1 == 1) %>%
  dplyr::select(IDPlots, HabCode)

VBI1_LSVI_Structuur <- calculateLSVI_dendroVBI1(plotHabtypes = plotHabtypesVBI1, niveau = "plot")

# ophalen bedekking soorten uit vegetatieopname
coverSpeciesVBI1 <- getCoverSpeciesVBI1(plotIDs = plotHabtypesVBI1$IDPlots)

# ophalen bedekking vegetatielagen
coverVegLayersVBI1 <- getCoverVeglayersVBI1(plotIDs = plotHabtypesVBI1$IDPlots)

# berekening indicatoren op basis van vegetatieopname
VBI1_LSVI_Vegetatie <- calculateLSVI_vegetatieopname(plotHabtypes = plotHabtypesVBI1, bedekkingSoorten = coverSpeciesVBI1, bedekkingVeglagen = coverVegLayersVBI1)

VBI1_LSVI <- bind_rows(VBI1_LSVI_Structuur, VBI1_LSVI_Vegetatie) %>%
              arrange(IDPlots, Criterium)


VBI1_LSVI$Periode <- 1
VBI2_LSVI$Periode <- 2

LSVI_AV <- bind_rows(VBI1_LSVI, VBI2_LSVI) %>%
            group_by(HabCode, Periode) %>%
            dplyr::mutate(RangNr = rank(IDPlots)) %>%
            ungroup() %>%
            arrange(IDPlots, Criterium)


LSVI_AV2 <- LSVI_AV
LSVI_AV2$HabCode <- "91xx"
LSVI_AV2$Drempelwaarde <- NA

LSVI_AV <- bind_rows(LSVI_AV, LSVI_AV2)

LSVI_AV$Gepaard <- LSVI_AV$IDPlots %in% gepaardePlots$IDPlots
LSVI_AV$SemiGepaard <- LSVI_AV$IDPlots %in% plotsVBI2$IDPlots

```


```{r changeNames, cache = TRUE}

LSVI_AV$Criterium <- factor(LSVI_AV$Criterium, levels = c("vegetatie", "habitatstructuur", "verstoring"))

LSVI_AV$Indicator <- gsub("_", " ",LSVI_AV$Indicator)
LSVI_AV$Indicator <- gsub("Of", " of ",LSVI_AV$Indicator)
LSVI_AV$Indicator <- gsub("En", " en ",LSVI_AV$Indicator)

LSVI_AV$AnalyseVariabele <- gsub("_", " ",LSVI_AV$AnalyseVariabele)
LSVI_AV$AnalyseVariabele <- gsub("Of", " of ",LSVI_AV$AnalyseVariabele)
LSVI_AV$AnalyseVariabele <- gsub("En", " en ",LSVI_AV$AnalyseVariabele)

LSVI_AV$BeoordelingTekst <- factor(ifelse(LSVI_AV$Beoordeling == 0, "Ongunstig", "Gunstig"))
colors_beoordeling <- c("Ongunstig" = inbo.rood, "Gunstig" = inbo.groen)

overzicht_LSVI_AV <- unique(LSVI_AV[,c("HabCode","Criterium","Indicator", "AnalyseVariabele", "Eenheid", "Drempelwaarde","VersieLSVI")])

overzicht_LSVI_AV <- dplyr::rename(overzicht_LSVI_AV, 'Drempel- waarde' = Drempelwaarde )

overzicht_LSVI_AV <- arrange(overzicht_LSVI_AV, Criterium)

# DataLSVI_AV <- LSVI_AV
# HabCode <- "2310"


```



```{r statsAV}
LSVI_AV_mean <- LSVI_AV %>%
  group_by(HabCode, Periode, Criterium, Indicator,  AnalyseVariabele, Eenheid, Drempelwaarde, Indicatortype) %>%
  do(mean_cl_boot(.$Waarde))

LSVI_AV_mean_gepaard <- LSVI_AV %>%
  filter(Gepaard) %>%
  group_by(HabCode, Periode, Criterium, Indicator,  AnalyseVariabele, Eenheid, Drempelwaarde, Indicatortype) %>%
  do(mean_cl_boot(.$Waarde))

LSVI_AV_mean_semiGepaard <- LSVI_AV %>%
  filter(SemiGepaard) %>%
  group_by(HabCode, Periode, Criterium, Indicator,  AnalyseVariabele, Eenheid, Drempelwaarde, Indicatortype) %>%
  do(mean_cl_boot(.$Waarde))

LSVI_AV_PropOng <-  LSVI_AV %>%
  group_by(HabCode, Periode, Criterium, Indicator,  AnalyseVariabele, Eenheid, Drempelwaarde, Indicatortype) %>%
  dplyr::summarise(AandeelOngunstig = round(1 - sum(Beoordeling,na.rm = TRUE)/sum(!is.na(Beoordeling)),2))

```




# Berekening aandeel gunstige plots per indicatoren en beoordeling


```{r calculateAV, cache = TRUE}

LSVI_Ind <-  dplyr::summarise(group_by(LSVI_AV, Periode, HabCode,  IDPlots, Criterium,Indicator, Gepaard, SemiGepaard),
                      BeoordelingCont = sum(Beoordeling)/n(),
                      Combinatie = unique(Combinatie))

LSVI_Ind$BeoordelingBinair <- ifelse(is.na(LSVI_Ind$Combinatie) | LSVI_Ind$Combinatie =="" ,LSVI_Ind$BeoordelingCont,
                                         ifelse(LSVI_Ind$Combinatie == "EN", LSVI_Ind$BeoordelingCont == 1,
                                                ifelse(LSVI_Ind$Combinatie == "OF",LSVI_Ind$BeoordelingCont > 0, NA )))

LSVI_Ind$BeoordelingTekst <- ifelse(LSVI_Ind$BeoordelingBinair == 0, "Ongunstig", "Gunstig")

LSVI_Ind <- dplyr::mutate(group_by(LSVI_Ind, HabCode),
                     Grens = 0.25 * n_distinct(IDPlots))

LSVI_Ind$IndicatorTekst <- factor(LSVI_Ind$Indicator)
levels(LSVI_Ind$IndicatorTekst) <- gsub(" ", "\n", levels(LSVI_Ind$IndicatorTekst))


```


```{r statsInd}
LSVI_Ind_Eval <- LSVI_Ind %>%
                group_by(Periode, HabCode, Criterium,Indicator, IndicatorTekst) %>%
                summarise(
                      AandeelOngunstig = (sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE))/ sum(!is.na(BeoordelingBinair)),
                      n = sum(!is.na(BeoordelingBinair)),
                      binom.test_p = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$p.value,
                      binom.test_est = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$estimate,
                      binom.test_lc = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$conf.int[1],
                      binom.test_rc = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$conf.int[2])

LSVI_Ind_Eval$Uitspraak <- ifelse(LSVI_Ind_Eval$binom.test_p > 0.05, "Unknown",
                                      ifelse(LSVI_Ind_Eval$AandeelOngunstig > 0.25, "Unfavourable", "Favourable" ))

LSVI_Ind_Eval_Gepaard <- LSVI_Ind %>%
                filter(Gepaard) %>%
                group_by(Periode, HabCode, Criterium,Indicator, IndicatorTekst) %>%
                summarise(
                      AandeelOngunstig = (sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE))/ sum(!is.na(BeoordelingBinair)),
                      n = sum(!is.na(BeoordelingBinair)),
                      binom.test_p = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$p.value,
                      binom.test_est = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$estimate,
                      binom.test_lc = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$conf.int[1],
                      binom.test_rc = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$conf.int[2])

LSVI_Ind_Eval_Gepaard$Uitspraak <- ifelse(LSVI_Ind_Eval_Gepaard$binom.test_p > 0.05, "Unknown",
                                      ifelse(LSVI_Ind_Eval_Gepaard$AandeelOngunstig > 0.25, "Unfavourable", "Favourable" ))

LSVI_Ind_Eval_SemiGepaard <- LSVI_Ind %>%
                filter(SemiGepaard) %>%
                group_by(Periode, HabCode, Criterium,Indicator, IndicatorTekst) %>%
                summarise(
                      AandeelOngunstig = (sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE))/ sum(!is.na(BeoordelingBinair)),
                      n = sum(!is.na(BeoordelingBinair)),
                      binom.test_p = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$p.value,
                      binom.test_est = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$estimate,
                      binom.test_lc = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$conf.int[1],
                      binom.test_rc = binom.test(sum(!is.na(BeoordelingBinair)) - sum(BeoordelingBinair,na.rm =TRUE), n = sum(!is.na(BeoordelingBinair)), p = 0.25)$conf.int[2])

LSVI_Ind_Eval_SemiGepaard$Uitspraak <- ifelse(LSVI_Ind_Eval_SemiGepaard$binom.test_p > 0.05, "Unknown",
                                      ifelse(LSVI_Ind_Eval_SemiGepaard$AandeelOngunstig > 0.25, "Unfavourable", "Favourable" ))

```










# Verkenning analysevariabelen

## Habitattype 9120

```{r verkenningAV9120, warning = FALSE, message = FALSE, results = 'asis'}

overzicht_indicatoren %>%
  filter(HabCode == "9120") %>%
  dplyr::select(-HabCode, -VersieLSVI) %>%
  kable()
  # kable(caption = "Overzicht analysevariabelen voor LSVI-versie3 voor habitattype 9120", 
  #       booktabs = T, 
  #       format = "latex") %>% 
  # collapse_rows(columns = 1:2) %>% 
  # kable_styling(latex_options = c("hold_position")) %>% 
  # kable_styling(font_size = 10) %>%
  # column_spec(5, width = "4em")

```


# vegetatie

```{r figuurVegetatieHist}

LSVI_AV %>%
  filter(SemiGepaard) %>%
  filter(Criterium == "vegetatie") %>%
  ggplot(aes(x=Waarde, fill = factor(Periode))) + geom_histogram(bins = 10, alpha = 0.5, position = "identity") + 
  geom_vline(data = filter(LSVI_AV, Criterium == "vegetatie") , aes(xintercept = Drempelwaarde))  +
  facet_grid(HabCode ~ AnalyseVariabele, scales = "free")
```

```{r figuurVegetatieHistGepaard}

LSVI_AV %>%
  filter(Gepaard) %>%
  filter(Criterium == "vegetatie") %>%
  ggplot(aes(x=Waarde, fill = factor(Periode))) + geom_histogram(bins = 10, alpha = 0.5, position = "identity") + 
  geom_vline(data = filter(LSVI_AV, Criterium == "vegetatie") , aes(xintercept = Drempelwaarde))  +
  facet_grid(HabCode ~ AnalyseVariabele, scales = "free")
```

```{r figuurVegetatieMeanAv, fig.height= 7}

LSVI_AV %>%
  filter(SemiGepaard) %>%
  filter(Criterium == "vegetatie") %>%
  ggplot(aes(x = factor(Periode), y = Waarde, fill = factor(Periode))) +
  # geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.2) +
  stat_summary(fun.data = "mean_cl_boot" ) +
  geom_hline(data = filter(LSVI_AV, Criterium == "vegetatie") , aes(yintercept = Drempelwaarde))  +
  facet_grid(HabCode ~ AnalyseVariabele  , scales = "free", labeller = labeller(AnalyseVariabele = label_wrap_gen(17))) + 
  coord_flip() +
  theme(strip.text = element_text(size=8), legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust = 1), axis.text = element_text(size=8))
  

```



```{r figuurVegetatieMeanAvGepaard, fig.height= 7}

#enkel vegetatieplots die al twee maal zijn opgemeten

missingVegVBI1Plots <- LSVI_AV %>%
  filter(AnalyseVariabele == "sleutelsoorten kruidlaag aantal") %>%
  filter(is.na(Waarde)) 

LSVI_AV %>%
  filter(Gepaard) %>%
  filter(!(IDPlots %in% missingVegVBI1Plots$IDPlots)) %>%
  filter(Indicator == "sleutelsoorten kruidlaag") %>%
  ggplot(aes(x = factor(Periode), y = Waarde, fill = factor(Periode))) +
  # geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.2) +
  stat_summary(fun.data = "mean_cl_boot" ) +
  geom_hline(data = filter(LSVI_AV, Indicator == "sleutelsoorten kruidlaag") , aes(yintercept = Drempelwaarde))  +
  facet_grid(HabCode ~ AnalyseVariabele  , scales = "free", labeller = labeller(AnalyseVariabele = label_wrap_gen(17))) + 
  coord_flip() +
  theme(strip.text = element_text(size=8), legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust = 1), axis.text = element_text(size=8))
  

```





```{r figuurVegetatieAandeelOngunstig, fig.cap= "Geschatte aandeel van habitat(sub)type dat ongunstig scoort voor de verschillende indicatoren van LSVI-versie3, de bijhoreden betrouwbaarheidsintervallen en de beoordeling op Vlaamse schaal bij significantieniveau van 0.05", fig.height= 6}

LSVI_Ind_Eval %>%
  filter(Criterium == "vegetatie") %>%
  ggplot(aes(x = ifelse(Periode == 1, "VBI1", "VBI2"), y= binom.test_est, ymin= binom.test_lc, ymax = binom.test_rc , colour = Uitspraak)) + 
  geom_point(size = 3) +
  geom_errorbar(width = 0) +
  facet_grid(HabCode ~ Indicator , scales = "free_y", space="free_y") + labs(colour = "Beoordeling Vlaamse schaal" , y = "Aandeel ongunstig") + 
  scale_colour_manual(values = c(inbo.groen, inbo.rood,inbo.grijs)) + 
  geom_hline(aes(yintercept = 0.25), colour = "black", size = 0.5, linetype = "dashed", alpha = 0.5)  +
  theme(strip.text.y = element_text(angle = 0), legend.position = "bottom", strip.text = element_text(size =8), axis.text = element_text(size =8)) + 
  coord_flip() +
  scale_y_continuous(breaks=c(0 ,0.5, 1), limits = c(0,1))

```




# habitatstructuur

```{r figuurhabitatstructuurHist}

LSVI_AV %>%
  filter(Criterium == "habitatstructuur") %>%
  ggplot(aes(x=Waarde, fill = factor(Periode))) + geom_histogram(bins = 10, alpha = 0.5, position = "identity") + 
  geom_vline(data = filter(LSVI_AV, Criterium == "habitatstructuur") , aes(xintercept = Drempelwaarde))  +
  facet_grid(HabCode ~ AnalyseVariabele, scales = "free")
```



```{r figuurhabitatstructuurMeanAv, fig.height= 7}

LSVI_AV %>%
  filter(Criterium == "habitatstructuur") %>%
  ggplot(aes(x = factor(Periode), y = Waarde, fill = factor(Periode))) +
  # geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.2) +
  stat_summary(fun.data = "mean_cl_boot" ) +
  geom_hline(data = filter(LSVI_AV, Criterium == "habitatstructuur") , aes(yintercept = Drempelwaarde))  +
  facet_grid(HabCode ~ AnalyseVariabele  , scales = "free", labeller = labeller(AnalyseVariabele = label_wrap_gen(17))) + 
  coord_flip() +
  theme(strip.text = element_text(size=8), legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust = 1), axis.text = element_text(size=8))
  

```



```{r aggergatiePerIndicator4, fig.cap= "Geschatte aandeel van habitat(sub)type dat ongunstig scoort voor de verschillende indicatoren van LSVI-versie3, de bijhoreden betrouwbaarheidsintervallen en de beoordeling op Vlaamse schaal bij significantieniveau van 0.05", fig.height= 6}

LSVI_Ind_Eval %>%
  filter(Criterium == "habitatstructuur") %>%
  ggplot(aes(x = ifelse(Periode == 1, "VBI1", "VBI2"), y= binom.test_est, ymin= binom.test_lc, ymax = binom.test_rc , colour = Uitspraak)) + 
  geom_point(size = 3) +
  geom_errorbar(width = 0) +
  facet_grid(HabCode ~ Indicator , scales = "free_y", space="free_y") + labs(colour = "Beoordeling Vlaamse schaal" , y = "Aandeel ongunstig") + 
  scale_colour_manual(values = c(inbo.groen, inbo.rood,inbo.grijs)) + 
  geom_hline(aes(yintercept = 0.25), colour = "black", size = 0.5, linetype = "dashed", alpha = 0.5)  +
  theme(strip.text.y = element_text(angle = 0), legend.position = "bottom", strip.text = element_text(size =8), axis.text = element_text(size =8)) + 
  coord_flip() +
  scale_y_continuous(breaks=c(0 ,0.5, 1), limits = c(0,1))

```





# verstoring

```{r figuurverstoringHist}

LSVI_AV %>%
  filter(Indicator == "invasieve exoten") %>%
  ggplot(aes(x=Waarde, fill = factor(Periode))) + geom_histogram(bins = 10, alpha = 0.5, position = "identity") + 
  geom_vline(data = filter(LSVI_AV, Indicator == "invasieve exoten") , aes(xintercept = Drempelwaarde))  +
  facet_grid(HabCode ~ AnalyseVariabele, scales = "free")
```



```{r figuurverstoringMeanAv, fig.height= 7}

LSVI_AV %>%
  filter(Criterium == "verstoring") %>%
  ggplot(aes(x = factor(Periode), y = Waarde, fill = factor(Periode))) +
  # geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.2) +
  stat_summary(fun.data = "mean_cl_boot" ) +
  geom_hline(data = filter(LSVI_AV, Criterium == "verstoring") , aes(yintercept = Drempelwaarde))  +
  facet_grid(HabCode ~ AnalyseVariabele  , scales = "free", labeller = labeller(AnalyseVariabele = label_wrap_gen(17))) + 
  coord_flip() +
  theme(strip.text = element_text(size=8), legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust = 1), axis.text = element_text(size=8))
  

```



```{r AandeelOngunstigVerstoring}

LSVI_Ind_Eval %>%
  filter(Criterium == "verstoring") %>%
  ggplot(aes(x = ifelse(Periode == 1, "VBI1", "VBI2"), y= binom.test_est, ymin= binom.test_lc, ymax = binom.test_rc , colour = Uitspraak)) + 
  geom_point(size = 3) +
  geom_errorbar(width = 0) +
  facet_grid(HabCode ~ Indicator , scales = "free_y", space="free_y") + labs(colour = "Beoordeling Vlaamse schaal" , y = "Aandeel ongunstig") + 
  scale_colour_manual(values = c(inbo.groen, inbo.rood,inbo.grijs)) + 
  geom_hline(aes(yintercept = 0.25), colour = "black", size = 0.5, linetype = "dashed", alpha = 0.5)  +
  theme(strip.text.y = element_text(angle = 0), legend.position = "bottom", strip.text = element_text(size =8), axis.text = element_text(size =8)) + 
  coord_flip() +
  scale_y_continuous(breaks=c(0 ,0.5, 1), limits = c(0,1))

```


```{r chechInvasieveExoten}


