---
title: 'Meetnet habitatkwaliteit: verkennende analyses'
author: "Toon Westra"
date: "juli 2017"
output:
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
    subtitle: "Tussentijds technisch rapport"
    reportnr: "Intern Rapport"
    citation_package: none
    keep_tex: yes
  bookdown::gitbook: default
site: bookdown::bookdown_site
header-includes: 
  - \usepackage{placeins}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
---


```{r results ='hide', echo = FALSE, message = FALSE, purl = FALSE, warning=FALSE}

library(knitr)
opts_chunk$set(
  echo = FALSE, 
  results = 'markup',
  eval = TRUE,
  cache = TRUE,
  autodep = TRUE,
  dev = "pdf",
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  warning = FALSE,
  error = TRUE,
  message = FALSE
)

library(pander) # best eerst knitr en daarna pas pander laden


#theme_set(theme_bw(base_size = 9))

```


```{r Rinit,  warning = FALSE, message = FALSE, results = 'hide', cache = FALSE}

source("../scripts/Omgevingsvariabelen_versie2016-10-12.R")
source("../scripts/LSVI/LSVI_functies.R") 

library(tidyr)
library(dplyr)
library(tibble)
library(stringr)
library(ggmap)
library(kableExtra)
```





